Clean code
Star-Academy/Team7-Codes pull request #1
Opened 2020-08-03 07:01 UTC by Parsa2820

2020-08-03 07:20 UTC, MahdiHma commented on Phase01/src/App.java
>                  public void accept(String t) {
پیاده‌سازی جالبی بود. نحوه خروجی دادنتان هم بسیار زیباس.

2020-08-03 07:38 UTC, mohammadhheidarzade reviewed
در کل کد خوبی بود پیچیدگی زیادی نداشت فقط یک سری کامنت ها اضافه بود که ذکر شد. موفق باشید 👍

2020-08-03 07:38 UTC, mohammadhheidarzade commented on Phase01/src/FileReader.java
>                  // System.out.println(line);
بهتر از کد هایی ناکارآمدی که کامنت شده است از فایل حذف شود :)

2020-08-03 07:39 UTC, MahdiHma reviewed
در کل بسیار خوب و تمیز زده شده. بجز چند مورد ناچیز بقیه موارد به خوبی رعایت شده.

2020-08-03 07:39 UTC, MahdiHma commented on Phase01/src/App.java
>          // for(String a : withPluses){
بهتر است این قسمت از  کد که کامنت نامفهومی است پاک شود.

2020-08-03 10:14 UTC, Parsa2820 commented on Phase01/src/FileReader.java
>                  // System.out.println(line);
اصلاح شد

2020-08-03 11:18 UTC, mostmand commented on Phase01/src/App.java
> +        //FileReader fileReader = new FileReader(invertedIndex, "/media/hassan/new part/code-star/EnglishData"); //Linux path
وظیفه‌ی تابع
main
فقط شروع برنامه است و کارهایی که انجام میشه باید به کلاس‌ها و تابع‌های دیگه سپرده بشن

2020-08-03 11:20 UTC, mostmand commented on Phase01/src/App.java
> +        result.forEach(new Consumer<String>(){
می‌تونید از لامبدا اکسپرشن استفاده کنید

2020-08-03 11:23 UTC, mostmand commented on Phase01/src/FileReader.java
> +                invertedIndex.add(line.toLowerCase(), document.getName());
فرض کنید بعد بخواید غیر از
lowercase
کردن یه نرمال سازی دیگه هم اضافه کنید الان هم اینجا از
toLowerCase
استفاده شده هم توی تابع 
main
اونجایی که تابع
advanceFind
صدا زده میشه

2020-08-03 11:26 UTC, mostmand commented on Phase01/src/SearchQuery.java
> +        String[] subs = query.split(" ");
این فرآیند اسپلیت کردن هم می تونه در کنار اون
toLowercase
که اشاره شد برن یه کلاس جدا بشن مثلاً
Tokenizer

2020-08-03 11:27 UTC, mostmand commented on Phase01/src/SearchQuery.java
> +        for (int i=0 ; i < subs.length ; i++){
از متغیر
i
استفاده ای نشده و میشه با 
foreach
جایگزین بشه

2020-08-03 11:27 UTC, mostmand reviewed
در کل بسیار عالی

2020-08-03 11:45 UTC, hassanzaker commented on Phase01/src/SearchQuery.java
> +        String[] subs = query.split(" ");
من در مورد اینکه فرآیند اسپلیت کردن کنار
 toLowerCase
 باشه زیاد موافقم نیستم.

2020-08-03 11:52 UTC, mohammadhheidarzade approved these changes
موردی ندیدم خیلی عالی  👍 و حقیقتا خیلی لذت بردم از کدتون 💯

2020-08-03 12:02 UTC, MahdiHma approved these changes
خدا قوت. بسیار عالی.

2020-08-03 12:46 UTC, mostmand commented on Phase01/src/SearchQuery.java
> +        String[] subs = query.split(" ");
اوکیه

2020-08-03 12:47 UTC, mostmand approved these changes

2020-08-03 13:16 UTC, hbehboudi commented on Phase01/src/App.java
>          try {
یه سری جاها یه خط فاصله بذارید خوانایی کد خیلی بیشتر میشه.
مثلا بهتره که بین بلاک‌های مختلف یه خط خالی باشه.

2020-08-03 13:23 UTC, hbehboudi commented on Phase01/src/FileReader.java
>      InvertedIndex invertedIndex;
بهتره سطح دسترسی‌هاشون رو ذکر کنید.

2020-08-03 13:39 UTC, hbehboudi approved these changes
خیلی عالی بود

2020-08-03 13:39 UTC, hbehboudi commented on Phase01/src/App.java
>          try {
یه سری جاها یه خط فاصله بذارید خوانایی کد خیلی بیشتر میشه.
مثلا بهتره که بین بلاک‌های مختلف یه خط خالی باشه.

2020-08-03 13:39 UTC, hbehboudi commented on Phase01/src/FileReader.java
> +    File file;
بهتره سطح دسترسی‌هاشون رو ذکر کنید.

2020-08-03 13:39 UTC, hbehboudi commented on Phase01/src/FileReader.java
>      public void readAllFiles(){
میشه به جای اینکه
path
رو به کانستراکتور داد به این تابع بدیم و همینجا فایل رو بسازیم.
مزیتش اینه که با ایجاد یک کلاس از چنتا فولدر هم میشه خوند.

2020-08-03 13:39 UTC, hbehboudi commented on Phase01/src/InvertedIndex.java
> +        set.forEach(new Consumer<String>(){
برای سادگی میتونید از لامبدا استفاده کنید

2020-08-03 15:42 UTC, nobletooth reviewed
خود اپلیکیشن خیلی خوب بود و استفاده از
reflection
هم باعث شده بتونید خیلی راحت شرط های جدیدی برای کلمات تعریف کنید.

2020-08-03 15:42 UTC, intenvy commented on Phase01/src/App.java
> +        // FileReader fileReader = new FileReader(invertedIndex, "D:\\Downloads\\SampleEnglishData\\EnglishData"); // Windows path
فایل دیتاست رو به داخل پروژه انتقال بدید تا بتونید از طریق مسیر های
relative
آدرس دهی کنید

همچنین در مسیرهای ویندوز هم میتوانید از / به جای \\\\ استفاده کنید، موردی نداره

2020-08-03 15:42 UTC, intenvy commented on Phase01/src/SearchQuery.java
> +        }
میونید متود جدیدی بسازید به نام
addWord(searchQuery, word)
 که سوییچ کیس را در آن انجام دهید و از حجم این متود بکاهید

2020-08-03 15:44 UTC, nobletooth approved these changes

2020-08-03 15:58 UTC, BijanEisapour requested changes
<p dir='rtl' align='right'>
خسته نباشید ❤
<br>
اینکه از کلاس کمکی مثل Tokenizer برای انجام یه سری کارا استفاده کردید خیلی خوب بود
<br>
دوتا تغییر بیشتر به ذهنم نرسید که اونا رو انجام بدید فک میکنم خیلی عالی بشه
</p>

2020-08-03 15:58 UTC, BijanEisapour commented on Phase01/src/InvertedIndex.java
> +            // Just no result for this word ... nothing important
<p dir='rtl' align='right'>
اگه Exception رخ داد، بهتره یه مسیر جایگزین برای برنامه یا کاربر مشخص کنی یا حداقل متن خطا رو نشون بدی تا کاربر متوجه شه چه کاری رو اشتباه انجام داده
</p>

2020-08-03 15:58 UTC, BijanEisapour commented on Phase01/src/InvertedIndex.java
>      }
<p dir='rtl' align='right'>
از اونجایی که اساس کار جست‌وجو هست به نظرم بهتره فقط یه متد براش تعریف کنی و تک‌کلمه یا چندکلمه بودن تاثیری تو فرایند اصلی نداشته باشه
</p>

2020-08-04 05:35 UTC, Parsa2820 commented on Phase01/src/InvertedIndex.java
> +            // Just no result for this word ... nothing important
<p dir="rtl">
این Exception مربوط به پیدا نشدن تنها یکی از لغات جستوجو هست که نیاز به اعلام به کاربر نیست. خطای مربوط به پیدا نشدن هیچ نتیجه جستوجو در تابغ advanceFind هندل شده.
</p>

2020-08-04 05:39 UTC, Parsa2820 commented on Phase01/src/InvertedIndex.java
>      }
<p dir="rtl">
این متد تو متدهای داخل کلاس استفاده شده. البته private بشه بهتره.
</p>

2020-08-04 05:45 UTC, Parsa2820 commented on Phase01/src/FileReader.java
> +    File file;
اصلاح شد

2020-08-04 05:52 UTC, Parsa2820 commented on Phase01/src/FileReader.java
>      public void readAllFiles(){
اصلاح شد

2020-08-04 05:56 UTC, Parsa2820 commented on Phase01/src/App.java
>          try {
اصلاح شد

2020-08-04 05:57 UTC, Parsa2820 commented on Phase01/src/InvertedIndex.java
> +        set.forEach(new Consumer<String>(){
انجام شد

2020-08-04 05:58 UTC, Parsa2820 commented on Phase01/src/App.java
> +        // FileReader fileReader = new FileReader(invertedIndex, "D:\\Downloads\\SampleEnglishData\\EnglishData"); // Windows path
بیشتر به خاطر شلوغ نشدن ریپوزیتوری فایل رو داخل ریپوزیتوری نذاشتیم

2020-08-04 06:02 UTC, Parsa2820 commented on Phase01/src/SearchQuery.java
> +        }
اوکی شد

2020-08-04 08:19 UTC, BijanEisapour approved these changes

2020-08-04 08:22 UTC, merged