Phase09 api
Star-Academy/Team7-Codes pull request #7
Opened 2020-09-01 06:42 UTC by Parsa2820

Closes https://github.com/Star-Academy/codestar-intern-issues/issues/90

2020-09-01 07:39 UTC, soleyman79 approved these changes
خسته نباشید. خیلی خوب بود

2020-09-01 07:39 UTC, soleyman79 commented on C#/Phase09/SearchApi/Controllers/SearchController.cs
> +            return Ok(result);
سلام
می شد کوئری رو توی 
body 
بفرستین. اینجوری یه کم اصولی تره

2020-09-01 07:51 UTC, MJavadHzr approved these changes
عااالی 👍  نکته خاصی به نظرم نرسید، خسته نباشید

2020-09-01 08:31 UTC, FarshidNooshi reviewed
خسته نباشید کد خوب بود 
فقط یک نکته:
 کلاسی برای تست کردن من ندیدم اینجا، آیا یونیت تست ندارید؟

2020-09-01 09:27 UTC, Parsa2820 commented
> 
> 
> عااالی 👍 نکته خاصی به نظرم نرسید، خسته نباشید

2020-09-01 09:45 UTC, Parsa2820 commented
> 
> 
> خسته نباشید کد خوب بود
> فقط یک نکته:
> کلاسی برای تست کردن من ندیدم اینجا، آیا یونیت تست ندارید؟

@FarshidNooshi 

وب ای پی آی داره از پکیج فاز قبلمون استفاده میکنه. واسه خود وب ای پی آی تست ننوشتیم

2020-09-01 09:56 UTC, FarshidNooshi commented
> > خسته نباشید کد خوب بود
> > فقط یک نکته:
> > کلاسی برای تست کردن من ندیدم اینجا، آیا یونیت تست ندارید؟
> 
> @FarshidNooshi
> 
> وب ای پی آی داره از پکیج فاز قبلمون استفاده میکنه. واسه خود وب ای پی آی تست ننوشتیم

اوکی

2020-09-01 09:56 UTC, FarshidNooshi approved these changes
موفق باشید

2020-09-04 20:35 UTC, mostmand requested changes

2020-09-04 20:35 UTC, mostmand commented on C#/Phase09/SearchApi/Controllers/SearchController.cs
> +            this.searchService = searchService;
احسنت از
DependencyInjection
استفاده کردید
👌

2020-09-04 20:35 UTC, mostmand commented on C#/Phase09/SearchApi/Controllers/SearchController.cs
> +            return Ok(result);
به نظر من اوکیه گوگل هم توی
query string
می‌فرسته عبارت جستجو رو

2020-09-04 20:35 UTC, mostmand commented on C#/Phase09/SearchApi/Services/SearchService.cs
> +            if (!initialized)
Initalizationتون
Thread-safe
نیست ممکنه چند تا ریکوئست با هم بیاد و چند بار
Initialization
صورت بگیره

2020-09-04 20:35 UTC, mostmand commented on C#/Phase09/SearchApi/appsettings.json
> +  "ElasticSearchAddress": "http://localhost:9200",
چرا نظیر این کانفیگ ها در
appsettings.Development.json
وجود ندارد؟

2020-09-04 20:36 UTC, mostmand commented on C#/Phase09/SearchApi/SearchApi.csproj
> +    <PackageReference Include="StarAcademy.Team7.InvertedIndexEngine" Version="1.1.0" />
احسنت به خاطر استفاده از نوگت

2020-09-05 04:57 UTC, Parsa2820 commented on C#/Phase09/SearchApi/Services/SearchService.cs
> +            if (!initialized)
<p dir="rtl">
dependency به صورت singleton تزریق شده
</p>

2020-09-05 05:20 UTC, Parsa2820 commented on C#/Phase09/SearchApi/appsettings.json
> +  "ElasticSearchAddress": "http://localhost:9200",
<p dir="rtl">
چون بدون پروفایل ران میکردیم حواسمون نبود. اضافه کردم. 👍
</p>

2020-09-05 09:47 UTC, mostmand commented on C#/Phase09/SearchApi/Services/SearchService.cs
> +            if (!initialized)
درسته ولی
Initialization
توی
Api
داره اتفاق میفته نه توی تابع سازنده

2020-09-05 09:48 UTC, mostmand requested changes
مشکل
Thread-safety
هنوز وجود داره

2020-09-06 05:39 UTC, Parsa2820 commented on C#/Phase09/SearchApi/Services/SearchService.cs
> +            if (!initialized)
درسته. اصلاح شد

2020-09-06 08:34 UTC, mostmand approved these changes

2020-09-07 08:38 UTC, hbehboudi approved these changes
خیلی عالی بود.👌👌👌
نکته‌ی خاصی به ذهنم نرسید.

2020-09-07 08:38 UTC, hbehboudi commented on C#/Phase09/SearchApi/Services/SearchService.cs
> +        private IConfiguration _config;
بهتره اینو
readonly
تعریف کنید.

2020-09-07 08:38 UTC, hbehboudi commented on C#/Phase09/SearchApi/Controllers/SearchController.cs
> +        private ISearchService searchService;
این رو هم بهتره
readonly
تعریف کنید.

2020-09-07 08:38 UTC, hbehboudi commented on C#/Phase09/SearchApi/Services/SearchService.cs
> +        }
اگه دوست داشتید توابع تک خطی رو اینجوری هم میتونید بنویسید.

```csharp
        public async Task<HashSet<Document>> Search(string query) =>
            await queryHandler.Find(new SearchQuery(query));
```

2020-09-07 09:52 UTC, merged